Repository prodigyeducation/branch-cleaner, pull requests merged in 2019-12, with the labels that each got.

#22 Update readme with new ENV var
  README.md
Labels: documentation

#23 Minor Tweaks to ESLint & Prettier
  .eslintrc.js
  .prettierrc.js
  functions/slack.js
  functions/webpack.functions.js
  package-lock.json
  src/slack/auth.js
  src/slack/auth.test.js
Labels: bug

#24 Take webpack.functions.js out of the functions directory
  .eslintrc.js
  package.json
  webpack.functions.js
Labels: bug

#26 Update netlify-lambda
  package-lock.json
  package.json
Labels: dependencies

#25 Add Code of Conduct
  docs/CODE_OF_CONDUCT.md
Labels: documentation

#29 Upgrade serialize-javascript to version 2.1.1
  package-lock.json
Labels: dependencies, security

#30 Set guidelines for repository contributors
  docs/CONTRIBUTING.md
  package.json
Labels: documentation
