Repository prodigyeducation/branch-cleaner, pull requests merged in 2019-11, with the labels that each got.

#9 Pin dependencies (fix #8)
  package-lock.json
  package.json
Labels: security

#11 Built functions shouldn't be checked into source control
  .gitignore
  lambda/remind.js
  lambda/slack.js
Labels: infra

#12 Option to exempt branches
  src/config.js
  src/github/filterStaleBranches.js
  src/github/filterStaleBranches.test.js
  src/github/findStaleBranches.js
  src/github/findStaleBranches.test.js
Labels: enhancement

#15 Stick to the LTS version of Node
  .nvmrc
  netlify.toml
Labels: infra

#16 Set up ESlint & Prettier
  .eslintignore
  .eslintrc.js
  .prettierignore
  .prettierrc.js
  functions/remind.js
  functions/slack.js
  package-lock.json
  package.json
  src/config.js
  src/deleteBranchThenUpdateMessage.js
  src/deleteBranchThenUpdateMessage.test.js
  src/github/deleteBranch.js
  src/github/deleteBranch.test.js
  src/github/fetchBranches.js
  src/github/fetchBranches.test.js
  src/github/filterStaleBranches.js
  src/github/filterStaleBranches.test.js
  src/github/findStaleBranches.js
  src/github/findStaleBranches.test.js
  src/remindOfStaleBranches.js
  src/remindOfStaleBranches.test.js
  src/remindOfTestBranches.js
  src/slack/chat.js
  src/slack/chat.test.js
  src/slack/composeBlocks.js
  src/slack/composeBlocks.test.js
  src/slack/feedbackMessage.js
  src/slack/publishMessages.js
  src/slack/publishMessages.test.js
Labels: enhancement, infra

#19 Put a missing return back
  src/slack/composeBlocks.js
Labels: bug

#21 Don't lint or format the lambda directory
  .eslintignore
  .prettierignore
Labels: bug

#20 Slack auth
  functions/slack.js
  functions/webpack.functions.js
  package-lock.json
  package.json
  src/config.js
  src/slack/auth.js
  src/slack/auth.test.js
  test.env
Labels: infra
